-- Auto-generated by Matugen

require('base16-colorscheme').setup({
  base00 = '#111318',
  base01 = '#0c0e13',
  base02 = '#191c20',
  base03 = '#43474e',
  base04 = '#c3c6cf',
  base05 = '#e1e2e9',
  base06 = '#2e3035',
  base07 = '#37393e',

  base08 = '#ffb4ab',
  base09 = '#d9bde3',
  base0A = '#bcc7db',
  base0B = '#a4c9fe',
  base0C = '#543f5e',
  base0D = '#d9bde3',
  base0E = '#d8e3f8',
  base0F = '#93000a',
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#204876',
  fg = '#111318',
})

set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#8d9199',
})

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#d9bde3',
})

set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#bcc7db',
})

vim.api.nvim_set_hl(0, 'Keyword', {
  fg = '#3a608f',
})

vim.api.nvim_set_hl(0, 'MsgArea', {
  bg = '#0c0e13',
  fg = '#a4c9fe',
})
